### ISSUE TITLE
Allocator should clean up google groups created by Sam when projects are created

### ISSUE THREAD

**Issue by helgridly** [broadinstitute/gpalloc#18]
@kyuksel to add details of what those groups look like

**Comment by kyuksel** [comment]
**Doug's recommendation:** Do what Rawls does [here](https://github.com/broadinstitute/rawls/blob/develop/core/src/main/scala/org/broadinstitute/dsde/rawls/monitor/CreatingBillingProjectMonitor.scala#L108), and the email addresses that come back from [syncPolicyToGoogle() calls](https://github.com/broadinstitute/rawls/blob/ef4caeebbcc10fd10469c77bd921553083cc5076/core/src/main/scala/org/broadinstitute/dsde/rawls/monitor/CreatingBillingProjectMonitor.scala#L102) are the ones we need to remove.

**Comment by helgridly** [comment]
Handled by #37 .
