### ISSUE TITLE
Rawls needs an endpoint to assume control of an already created billing project

### ISSUE THREAD

**Issue by helgridly** [broadinstitute/gpalloc#7]
This is work in Rawls but I figured we should track it here.

NOTE: And an endpoint to forget it ever assumed control of it.

I thought this might be difficult, but the Doge says: "Assuming project is created right, 1 row in rawls db, create resource in sam."

We should consider leaving the endpoint undocumented in Swagger / admin-only / otherwise secret.

**Comment by kyuksel** [comment]
> NOTE: And an endpoint to forget it ever assumed control of it.

This won't be done for two reasons:

1. We're not worried about the clutter generated in Rawls and Sam databases, which will be cleaned up when the FIAB is shut down.

2. Sam doesn't provide a way to delete billing projects.

Consequently, GPAlloc will need to clean up the Google groups generated by Sam as part of resource generation (tracked in #18).

**Comment by helgridly** [comment]
We have to solve this _somehow_. If `withCleanBillingProject` calls `GPAlloc.release()` after running the `op()`, it'll leave the rawls db in a bad state for the next test in the FiaB sequence.

Possible solutions:
1. Have the FiaB tests call release for all requested BPs at the end of the _entire_ test run. This will mean FiaBs hold on to multiple projects and only return them to the pool when tests complete.
2. Somehow drop the rawls and sam dbs inside `withCleanBillingProject`.

**Comment by kyuksel** [comment]
Good point! If I understand the scheme correctly`2.` sounds problematic due to race conditions. `1.` sounds good if it's not too difficult to implement.

**Comment by kyuksel** [comment]
Addressed in https://github.com/broadinstitute/rawls/pull/848
